Pharmacy System API new /prices-v2 operation
trifork/apoteksapp-documentation pull request #15
Opened 2021-03-17 15:28 UTC by jehtrifork

2021-03-17 15:29 UTC, hhstrifork approved these changes

2021-03-18 08:05 UTC, jhntrifork requested changes
Et par forslag til præciseringer eller fint.

2021-03-18 08:48 UTC, jehtrifork commented on pharmacy-system-api/suggested-pharmacy-system-api.yml
> +  /api/v1/pharmacy/{pharmacyNumber}/prices-v2:
Ja. `/api/v1` skulle egentlig have været specificeret som base-path i stedet for som en del af operation-path'en. Og da vi laver den nye operation som en udvidelse til det eksisterende API (modsat et komplet `/api/v2`-rework), så er det umiddelbart den bedste måde at sætte `-v2` i slutningen af operation-path. Man kunne også fx bruge en Content-Type header til at skelne, men det er mere gennemskueligt, at sætte det i operation-path.

2021-03-18 08:57 UTC, jehtrifork commented on pharmacy-system-api/suggested-pharmacy-system-api.yml
> +          or not. This parameter does only affect the reimbursement calculation and not the price."
Fixed.

2021-03-18 08:58 UTC, jehtrifork commented on pharmacy-system-api/suggested-pharmacy-system-api.yml
> +        - totalPurchase
Fixed.

2021-03-18 09:23 UTC, merged